# Generated by Django 2.2.14 on 2021-01-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210109_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
